<?php

@include_once 'auth.php';

function ƒ1($t = 'x', $l = 5) {
    $Ω = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    return substr(str_shuffle(str_repeat($Ω, ceil($l / strlen($Ω)))), 0, $l);
}

function ♻️($🕒, $🧠) {
    global $conn;
    $🐢 = 1;
    $🌀 = ƒ1('alnum', 5);
    $⚿ = $🧠 . '-' . $🕒 . '-' . $🌀;

    $a = strrev("eman");
    $b = strtolower("PUBG");

    $x = $conn->prepare("INSERT INTO keys_code (user_key, duration, game, max_devices, created_at, registrator) VALUES (?, ?, '$b', ?, NOW(), ?)");
    $x->bind_param("siss", $⚿, $🕒, $🐢, $🧠);
    $x->execute();
    $x->close();

    $💬 = "✨ **LICENSE KEY GENERATED** ✨\n\n" .
           "🎮 **Game:** BGMI\n" .
           "⏳ **Duration:** $🕒 Hours\n" .
           "🔑 **License Key:**\n`$⚿`\n" .
           "📱 **Max Devices:** $🐢\n" .
           "👤 **Generated by:** $🧠\n\n" .
           "⚠️ **Important Note:**\n" .
           "⏱ Timer starts when key is first used\n" .
           "🔒 Keep your key safe and private\n" .
           "📞 Contact support if you face issues";
    return $💬;
}

function ⌛($🪪) {
    global $conn;
    $stmt = $conn->prepare("SELECT username FROM users WHERE fullname = ?");
    $stmt->bind_param("s", $🪪);
    $stmt->execute();
    $stmt->bind_result($🧾);
    $stmt->fetch();
    $stmt->close();
    return $🧾;
}

$🧻 = file_get_contents("php://input");
$📦 = json_decode($🧻, TRUE);

function ✉️($🧿, $📝, $🧾 = null) {
    global $website;
    $📬 = $website . "/sendMessage?chat_id=$🧿&text=" . urlencode($📝);
    if ($🧾) $📬 .= "&reply_markup=" . urlencode($🧾);
    @file_get_contents($📬);
}

function 🧲($cbid, $txt = null) {
    global $website;
    $uri = $website . "/answerCallbackQuery?callback_query_id=$cbid";
    if ($txt) $uri .= "&text=" . urlencode($txt);
    @file_get_contents($uri);
}

// Owner verification function
function 🔒($🆔) {
    global $ownerID;
    return $🆔 == $ownerID;
}

// Check if command is admin-only
function 👑($🖊️) {
    global $adminCommands;
    foreach ($adminCommands as $cmd) {
        if (strpos($🖊️, $cmd) === 0) {
            return true;
        }
    }
    return false;
}

// Add user function (owner only)
function 👤➕($🧿, $targetUsername, $targetFullname) {
    global $conn;
    
    // Check if user already exists
    $check = $conn->prepare("SELECT id_users FROM users WHERE username = ?");
    $check->bind_param("s", $targetUsername);
    $check->execute();
    $result = $check->get_result();
    
    if ($result->num_rows > 0) {
        return "❌ User already exists!";
    }
    
    // Add new user with proper database structure
    $stmt = $conn->prepare("INSERT INTO users (username, fullname, email, reset_link_token, exp_date, level, saldo, status, uplink, password, user_ip, created_at, expiration_date) VALUES (?, ?, '', '', '', 1, 0, 1, 'Bot', '', '', NOW(), '2050-01-01 00:00:00')");
    $stmt->bind_param("ss", $targetUsername, $targetFullname);
    
    if ($stmt->execute()) {
        return "✅ User $targetUsername added successfully!";
    } else {
        return "❌ Failed to add user!";
    }
}

// Remove user function (owner only)
function 👤➖($🧿, $targetUsername) {
    global $conn;
    
    $stmt = $conn->prepare("DELETE FROM users WHERE username = ?");
    $stmt->bind_param("s", $targetUsername);
    
    if ($stmt->execute() && $stmt->affected_rows > 0) {
        return "✅ User $targetUsername removed successfully!";
    } else {
        return "❌ User not found or failed to remove!";
    }
}

// List all users function (owner only)
function 👥📋() {
    global $conn;
    
    $result = $conn->query("SELECT username, fullname, created_at FROM users ORDER BY created_at DESC");
    
    if ($result->num_rows == 0) {
        return "📝 No users found.";
    }
    
    $userList = "👥 **User List:**\n\n";
    while ($row = $result->fetch_assoc()) {
        $userList .= "👤 {$row['username']} ({$row['fullname']})\n";
        $userList .= "📅 Added: {$row['created_at']}\n\n";
    }
    
    return $userList;
}

// Get bot statistics (owner only)
function 📊() {
    global $conn;
    
    $userCount = $conn->query("SELECT COUNT(*) as count FROM users")->fetch_assoc()['count'];
    $keyCount = $conn->query("SELECT COUNT(*) as count FROM keys_code")->fetch_assoc()['count'];
    $todayKeys = $conn->query("SELECT COUNT(*) as count FROM keys_code WHERE DATE(created_at) = CURDATE()")->fetch_assoc()['count'];
    $activeKeys = $conn->query("SELECT COUNT(*) as count FROM keys_code WHERE status = 1")->fetch_assoc()['count'];
    
    return "📊 **Bot Statistics:**\n\n" .
           "👥 Total Users: $userCount\n" .
           "🔑 Total Keys Generated: $keyCount\n" .
           "🔑 Active Keys: $activeKeys\n" .
           "📈 Keys Generated Today: $todayKeys";
}

// Update bot token function (owner only)
function 🔄🤖($newToken) {
    $authFile = __DIR__ . '/auth.php';
    $content = file_get_contents($authFile);
    
    // Replace the bot token
    $pattern = '/\$botToken = \'[^\']+';
    $replacement = "\$botToken = '$newToken'";
    $newContent = preg_replace($pattern, $replacement, $content);
    
    if (file_put_contents($authFile, $newContent)) {
        return "✅ Bot token updated successfully! Restart the bot to apply changes.";
    } else {
        return "❌ Failed to update bot token!";
    }
}

// Toggle mod status function (owner only)
function 🔄🎮() {
    global $conn;
    
    $result = $conn->query("SELECT status FROM onoff WHERE id = 1");
    $currentStatus = $result->fetch_assoc()['status'];
    
    $newStatus = ($currentStatus === 'on') ? 'off' : 'on';
    $stmt = $conn->prepare("UPDATE onoff SET status = ? WHERE id = 1");
    $stmt->bind_param("s", $newStatus);
    
    if ($stmt->execute()) {
        return "✅ Mod status changed to: **$newStatus**";
    } else {
        return "❌ Failed to update mod status!";
    }
}

// Get mod info function (owner only)
function 🎮📝() {
    global $conn;
    
    $modResult = $conn->query("SELECT modname FROM modname WHERE id = 1")->fetch_assoc();
    $statusResult = $conn->query("SELECT status FROM onoff WHERE id = 1")->fetch_assoc();
    $ftextResult = $conn->query("SELECT _ftext FROM _ftext WHERE id = 1")->fetch_assoc();
    
    $modName = $modResult['modname'] ?? 'Unknown';
    $status = $statusResult['status'] ?? 'Unknown';
    $ftext = $ftextResult['_ftext'] ?? 'Unknown';
    
    return "🎮 **Mod Information:**\n\n" .
           "📝 Mod Name: $modName\n" .
           "🟢 Status: $status\n" .
           "📝 Info: $ftext";
}

// Create custom key function (owner only)
function 🔑➕($customKey, $duration, $registrator = 'Owner') {
    global $conn;
    
    // Check if key already exists
    $check = $conn->prepare("SELECT id_keys FROM keys_code WHERE user_key = ?");
    $check->bind_param("s", $customKey);
    $check->execute();
    $result = $check->get_result();
    
    if ($result->num_rows > 0) {
        return "❌ Key already exists: $customKey";
    }
    
    // Create custom key
    $maxDevices = 1;
    $game = strtolower("PUBG");
    
    $stmt = $conn->prepare("INSERT INTO keys_code (user_key, duration, game, max_devices, created_at, registrator, status) VALUES (?, ?, ?, ?, NOW(), ?, 1)");
    $stmt->bind_param("sisis", $customKey, $duration, $game, $maxDevices, $registrator);
    
    if ($stmt->execute()) {
        return "✅ **Custom Key Created!**\n\n" .
               "🔑 Key: $customKey\n" .
               "⏳ Duration: $duration Hours\n" .
               "🎮 Game: BGMI\n" .
               "📱 Max Devices: $maxDevices\n" .
               "👤 Created by: $registrator";
    } else {
        return "❌ Failed to create custom key!";
    }
}

// Delete key function (owner only)
function 🔑➖($keyToDelete) {
    global $conn;
    
    // Check if key exists
    $check = $conn->prepare("SELECT id_keys, registrator FROM keys_code WHERE user_key = ?");
    $check->bind_param("s", $keyToDelete);
    $check->execute();
    $result = $check->get_result();
    
    if ($result->num_rows == 0) {
        return "❌ Key not found: $keyToDelete";
    }
    
    $keyData = $result->fetch_assoc();
    
    // Delete the key
    $stmt = $conn->prepare("DELETE FROM keys_code WHERE user_key = ?");
    $stmt->bind_param("s", $keyToDelete);
    
    if ($stmt->execute()) {
        return "✅ **Key Deleted Successfully!**\n\n" .
               "🔑 Deleted Key: $keyToDelete\n" .
               "👤 Was created by: {$keyData['registrator']}";
    } else {
        return "❌ Failed to delete key!";
    }
}

// Show all keys function (owner only)
function 🔑📋($limit = 20) {
    global $conn;
    
    $result = $conn->query("SELECT user_key, duration, registrator, status, created_at FROM keys_code ORDER BY created_at DESC LIMIT $limit");
    
    if ($result->num_rows == 0) {
        return "📝 No keys found in database.";
    }
    
    $keyList = "🔑 **All Keys (Last $limit):**\n\n";
    $count = 1;
    
    while ($row = $result->fetch_assoc()) {
        $status = $row['status'] == 1 ? '🟢 Active' : '🔴 Inactive';
        $keyList .= "$count. 🔑 {$row['user_key']}\n";
        $keyList .= "   ⏳ Duration: {$row['duration']} hrs\n";
        $keyList .= "   👤 Creator: {$row['registrator']}\n";
        $keyList .= "   $status\n";
        $keyList .= "   📅 Created: {$row['created_at']}\n\n";
        $count++;
    }
    
    $totalKeys = $conn->query("SELECT COUNT(*) as count FROM keys_code")->fetch_assoc()['count'];
    $keyList .= "📊 Total Keys in Database: $totalKeys";
    
    return $keyList;
}

// Reset single key function (owner only)
function 🔄🔑($keyToReset) {
    global $conn;
    
    // Check if key exists
    $check = $conn->prepare("SELECT id_keys, registrator FROM keys_code WHERE user_key = ?");
    $check->bind_param("s", $keyToReset);
    $check->execute();
    $result = $check->get_result();
    
    if ($result->num_rows == 0) {
        return "❌ Key not found: $keyToReset";
    }
    
    $keyData = $result->fetch_assoc();
    
    // Reset the key (clear devices, set status active, clear expired_date)
    $stmt = $conn->prepare("UPDATE keys_code SET devices = NULL, status = 1, expired_date = NULL, updated_at = NOW() WHERE user_key = ?");
    $stmt->bind_param("s", $keyToReset);
    
    if ($stmt->execute()) {
        return "✅ **Key Reset Successfully!**\n\n" .
               "🔑 Reset Key: $keyToReset\n" .
               "👤 Created by: {$keyData['registrator']}\n" .
               "🔄 Status: Active\n" .
               "📱 Devices: Cleared\n" .
               "⏰ Expiry: Cleared";
    } else {
        return "❌ Failed to reset key!";
    }
}

// Reset all keys function (owner only)
function 🔄🔑📋() {
    global $conn;
    
    // Get count before reset
    $totalKeys = $conn->query("SELECT COUNT(*) as count FROM keys_code")->fetch_assoc()['count'];
    
    if ($totalKeys == 0) {
        return "📝 No keys found to reset.";
    }
    
    // Reset all keys
    $stmt = $conn->prepare("UPDATE keys_code SET devices = NULL, status = 1, expired_date = NULL, updated_at = NOW()");
    
    if ($stmt->execute()) {
        $affectedRows = $stmt->affected_rows;
        return "✅ **All Keys Reset Successfully!**\n\n" .
               "🔑 Total Keys Reset: $affectedRows\n" .
               "🔄 All keys are now active\n" .
               "📱 All devices cleared\n" .
               "⏰ All expiry dates cleared";
    } else {
        return "❌ Failed to reset all keys!";
    }
}

if (isset($📦["message"])) {
    $🧿 = $📦["message"]["chat"]["id"];
    $🆔 = $📦["message"]["from"]["id"];
    $🖊️ = $📦["message"]["text"];

    // Check if command is admin-only and user is not owner
    if (👑($🖊️) && !🔒($🆔)) {
        ✉️($🧿, "❌ You don't have permission to use this command. Only the bot owner can access admin functions.");
        die();
    }

    // For non-admin commands, check if user exists in database (skip check for owner)
    if (!👑($🖊️) && !🔒($🆔)) {
        $🧠 = ⌛($🆔);
        if (!$🧠) {
            ✉️($🧿, "You do not have access to use this bot.");
            die();
        }
    }

    // Handle admin commands
    if ($🖊️ === "/start" && 🔒($🆔)) {
        $⌨️ = [
            'keyboard' => [
                [['text' => '🔑 Generate Key'], ['text' => '🔧 Admin Panel']],
                [['text' => '📊 Quick Stats'], ['text' => '⚙️ Settings']]
            ],
            'resize_keyboard' => true,
            'one_time_keyboard' => false
        ];
        $🖼️ = json_encode($⌨️);
        ✉️($🧿, "👑 **Welcome Boss!** 👑\n\n🎆 You have full admin access to the bot.\n💼 Choose what you'd like to do:", $🖼️);
    }
    else if ($🖊️ === "/start") {
        $⌨️ = [
            'keyboard' => [
                [['text' => '🔑 Generate Key']],
                [['text' => '📞 Contact Support']]
            ],
            'resize_keyboard' => true,
            'one_time_keyboard' => false
        ];
        $🖼️ = json_encode($⌨️);
        ✉️($🧿, "👋 **Welcome to BGMI Key Generator!**\n\n🎮 Generate license keys for BGMI mod access.\n🔑 Click the button below to get started:", $🖼️);
    }

    if ($🖊️ === "🔧 Admin Panel" && 🔒($🆔)) {
        $adminKeyboard = [
            'keyboard' => [
                [['text' => '👥 User Management'], ['text' => '🔑 Key Management']],
                [['text' => '🎮 Mod Control'], ['text' => '📊 Statistics']],
                [['text' => '⚙️ System Settings']],
                [['text' => '⬅️ Back to Main Menu']]
            ],
            'resize_keyboard' => true,
            'one_time_keyboard' => false
        ];
        ✉️($🧿, "🔧 **Admin Control Panel** 🔧\n\n💼 Select a management category:", json_encode($adminKeyboard));
    }

    if ($🖊️ === "⬅️ Back to Main Menu") {
        $⌨️ = [
            'keyboard' => [
                [['text' => '🔑 Generate Key'], ['text' => '🔧 Admin Panel']],
                [['text' => '📊 Quick Stats'], ['text' => '⚙️ Settings']]
            ],
            'resize_keyboard' => true,
            'one_time_keyboard' => false
        ];
        $🖼️ = json_encode($⌨️);
        ✉️($🧿, "🏠 **Main Menu** 🏠\n\n👑 Welcome back, Boss!", $🖼️);
    }

    // Sub-menu handlers
    if ($🖊️ === "👥 User Management" && 🔒($🆔)) {
        $userKeyboard = [
            'keyboard' => [
                [['text' => '/adduser'], ['text' => '/removeuser']],
                [['text' => '/listusers']],
                [['text' => '⬅️ Back to Admin Panel']]
            ],
            'resize_keyboard' => true,
            'one_time_keyboard' => false
        ];
        ✉️($🧿, "👥 **User Management** 👥\n\n📝 Manage bot users and permissions:", json_encode($userKeyboard));
    }

    if ($🖊️ === "🔑 Key Management" && 🔒($🆔)) {
        $keyKeyboard = [
            'keyboard' => [
                [['text' => '/createkey'], ['text' => '/deletekey']],
                [['text' => '/showkeys'], ['text' => '/resetkey']],
                [['text' => '/resetallkeys']],
                [['text' => '⬅️ Back to Admin Panel']]
            ],
            'resize_keyboard' => true,
            'one_time_keyboard' => false
        ];
        ✉️($🧿, "🔑 **Key Management** 🔑\n\n🔧 Create, modify, and manage license keys:", json_encode($keyKeyboard));
    }

    if ($🖊️ === "🎮 Mod Control" && 🔒($🆔)) {
        $modKeyboard = [
            'keyboard' => [
                [['text' => '/modstatus'], ['text' => '/modinfo']],
                [['text' => '⬅️ Back to Admin Panel']]
            ],
            'resize_keyboard' => true,
            'one_time_keyboard' => false
        ];
        ✉️($🧿, "🎮 **Mod Control** 🎮\n\n🔧 Manage mod status and information:", json_encode($modKeyboard));
    }

    if ($🖊️ === "📊 Statistics" && 🔒($🆔)) {
        $statsKeyboard = [
            'keyboard' => [
                [['text' => '/stats']],
                [['text' => '⬅️ Back to Admin Panel']]
            ],
            'resize_keyboard' => true,
            'one_time_keyboard' => false
        ];
        ✉️($🧿, "📊 **Statistics Dashboard** 📊\n\n📈 View detailed bot analytics:", json_encode($statsKeyboard));
    }

    if ($🖊️ === "⚙️ System Settings" && 🔒($🆔)) {
        $settingsKeyboard = [
            'keyboard' => [
                [['text' => '/settoken']],
                [['text' => '⬅️ Back to Admin Panel']]
            ],
            'resize_keyboard' => true,
            'one_time_keyboard' => false
        ];
        ✉️($🧿, "⚙️ **System Settings** ⚙️\n\n🔧 Configure bot system settings:", json_encode($settingsKeyboard));
    }

    if ($🖊️ === "⬅️ Back to Admin Panel" && 🔒($🆔)) {
        $adminKeyboard = [
            'keyboard' => [
                [['text' => '👥 User Management'], ['text' => '🔑 Key Management']],
                [['text' => '🎮 Mod Control'], ['text' => '📊 Statistics']],
                [['text' => '⚙️ System Settings']],
                [['text' => '⬅️ Back to Main Menu']]
            ],
            'resize_keyboard' => true,
            'one_time_keyboard' => false
        ];
        ✉️($🧿, "🔧 **Admin Control Panel** 🔧\n\n💼 Select a management category:", json_encode($adminKeyboard));
    }

    // Quick Stats button
    if ($🖊️ === "📊 Quick Stats" && 🔒($🆔)) {
        $response = 📊();
        ✉️($🧿, $response);
    }

    // Settings button  
    if ($🖊️ === "⚙️ Settings" && 🔒($🆔)) {
        $settingsKeyboard = [
            'keyboard' => [
                [['text' => '/settoken']],
                [['text' => '⬅️ Back to Main Menu']]
            ],
            'resize_keyboard' => true,
            'one_time_keyboard' => false
        ];
        ✉️($🧿, "⚙️ **Quick Settings** ⚙️\n\n🔧 System configuration options:", json_encode($settingsKeyboard));
    }

    // Contact Support for regular users
    if ($🖊️ === "📞 Contact Support") {
        ✉️($🧿, "📞 **Contact Support** 📞\n\n👨‍💻 For technical support or questions:\n📧 Email: support@example.com\n📱 Telegram: @admin\n\n🕰️ Response time: 24-48 hours");
    }

    // Admin command handlers
    if (strpos($🖊️, '/adduser') === 0 && 🔒($🆔)) {
        $parts = explode(' ', $🖊️, 3);
        if (count($parts) === 3) {
            $response = 👤➕($🧿, $parts[1], $parts[2]);
            ✉️($🧿, $response);
        } else {
            ✉️($🧿, "📝 Usage: /adduser username fullname\nExample: /adduser john123 John Doe");
        }
    }

    if (strpos($🖊️, '/removeuser') === 0 && 🔒($🆔)) {
        $parts = explode(' ', $🖊️, 2);
        if (count($parts) === 2) {
            $response = 👤➖($🧿, $parts[1]);
            ✉️($🧿, $response);
        } else {
            ✉️($🧿, "📝 Usage: /removeuser username\nExample: /removeuser john123");
        }
    }

    if ($🖊️ === '/listusers' && 🔒($🆔)) {
        $response = 👥📋();
        ✉️($🧿, $response);
    }

    if ($🖊️ === '/stats' && 🔒($🆔)) {
        $response = 📊();
        ✉️($🧿, $response);
    }

    if (strpos($🖊️, '/settoken') === 0 && 🔒($🆔)) {
        $parts = explode(' ', $🖊️, 2);
        if (count($parts) === 2) {
            $response = 🔄🤖($parts[1]);
            ✉️($🧿, $response);
        } else {
            ✉️($🧿, "📝 Usage: /settoken YOUR_BOT_TOKEN\nExample: /settoken 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11");
        }
    }

    if ($🖊️ === '/modstatus' && 🔒($🆔)) {
        $response = 🔄🎮();
        ✉️($🧿, $response);
    }

    if ($🖊️ === '/modinfo' && 🔒($🆔)) {
        $response = 🎮📝();
        ✉️($🧿, $response);
    }

    // Key Management Commands
    if (strpos($🖊️, '/createkey') === 0 && 🔒($🆔)) {
        $parts = explode(' ', $🖊️, 3);
        if (count($parts) === 3) {
            $customKey = $parts[1];
            $duration = (int)$parts[2];
            if ($duration > 0) {
                $response = 🔑➕($customKey, $duration, 'Owner');
                ✉️($🧿, $response);
            } else {
                ✉️($🧿, "❌ Duration must be a positive number!");
            }
        } else {
            ✉️($🧿, "📝 Usage: /createkey CUSTOM_KEY DURATION_HOURS\nExample: /createkey MYKEY123 24");
        }
    }

    if (strpos($🖊️, '/deletekey') === 0 && 🔒($🆔)) {
        $parts = explode(' ', $🖊️, 2);
        if (count($parts) === 2) {
            $response = 🔑➖($parts[1]);
            ✉️($🧿, $response);
        } else {
            ✉️($🧿, "📝 Usage: /deletekey KEY_TO_DELETE\nExample: /deletekey MYKEY123");
        }
    }

    if ($🖊️ === '/showkeys' && 🔒($🆔)) {
        $response = 🔑📋(20);
        ✉️($🧿, $response);
    }

    if (strpos($🖊️, '/resetkey') === 0 && 🔒($🆔)) {
        $parts = explode(' ', $🖊️, 2);
        if (count($parts) === 2) {
            $response = 🔄🔑($parts[1]);
            ✉️($🧿, $response);
        } else {
            ✉️($🧿, "📝 Usage: /resetkey KEY_TO_RESET\nExample: /resetkey MYKEY123");
        }
    }

    if ($🖊️ === '/resetallkeys' && 🔒($🆔)) {
        $response = 🔄🔑📋();
        ✉️($🧿, $response);
    }

    if ($🖊️ === "🔑 Generate Key") {
        $⌛ = [
            'inline_keyboard' => [
                [['text' => '⏱️ 2 Hours', 'callback_data' => '2 Hours'], ['text' => '⏲️ 5 Hours', 'callback_data' => '5 Hours']],
                [['text' => '📅 1 Day', 'callback_data' => '1 Day'], ['text' => '📊 3 Days', 'callback_data' => '3 Days']],
                [['text' => '📆 7 Days', 'callback_data' => '7 Days'], ['text' => '📎 14 Days', 'callback_data' => '14 Days']],
                [['text' => '📈 30 Days', 'callback_data' => '30 Days'], ['text' => '📊 60 Days', 'callback_data' => '60 Days']]
            ]
        ];
        ✉️($🧿, "🔑 **Key Generation** 🔑\n\n🎮 Select duration for your BGMI license key:\n\n⏰ **Available Durations:**\n• Short term: 2-5 hours\n• Daily: 1-3 days\n• Weekly: 7-14 days\n• Monthly: 30-60 days", json_encode($⌛));
    }
}

if (isset($📦["callback_query"])) {
    $⛏️ = $📦["callback_query"]["id"];
    $🧿 = $📦["callback_query"]["message"]["chat"]["id"];
    $🆔 = $📦["callback_query"]["from"]["id"];
    $🔑 = $📦["callback_query"]["data"];

    // For callback queries, check user access (owner or authorized user)
    if (!🔒($🆔)) {
        $🧠 = ⌛($🆔);
        if (!$🧠) {
            ✉️($🧿, "You do not have access to use this bot.");
            🧲($⛏️, "Access denied!");
            exit();
        }
    }

    $🎚️ = [
        '2 Hours' => 2,
        '5 Hours' => 5,
        '1 Day' => 24,
        '3 Days' => 72,
        '7 Days' => 168,
        '14 Days' => 336,
        '30 Days' => 720,
        '60 Days' => 1440
    ];

    if (array_key_exists($🔑, $🎚️)) {
        // Get username for key generation
        $🧠 = 🔒($🆔) ? 'Owner' : ⌛($🆔);
        $🚪 = ♻️($🎚️[$🔑], $🧠);
        ✉️($🧿, $🚪);
        🧲($⛏️, "Key generated!");
    }
}
?>
